# Generated by Django 3.1.7 on 2021-03-16 12:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotList',
            fields=[
                ('icon', models.TextField(blank=True, null=True)),
                ('url', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('api_url', models.TextField(blank=True, null=True)),
                ('discord', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('supported_features', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('api_token', models.TextField(default=uuid.UUID('7a79a73a-fe5b-45c2-af0a-df6ff3d917a8'))),
                ('queue', models.BooleanField(default=False, null=True)),
                ('owners', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'bot_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotListFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('iname', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('positive', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bot_list_feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotListApi',
            fields=[
                ('url', models.OneToOneField(db_column='url', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='NGBBAdmin.botlist')),
                ('method', models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PATCH'), (4, 'PUT'), (5, 'DELETE')], null=True)),
                ('feature', models.IntegerField(choices=[(1, 'Get Bot'), (2, 'Post Stats')], default=1, null=True)),
                ('supported_fields', models.JSONField(help_text='Format of each key, valae is NGBB_KEY: LIST_KEY where NGBB_KEY is the key used by NGBB and LIST_KEY is the key used by the list')),
                ('api_path', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'bot_list_api',
                'managed': False,
            },
        ),
    ]
