# Generated by Django 3.1.7 on 2021-03-16 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGBBAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('0aa1289e-d6ee-4714-ba04-ce4f2e8e7883')),
        ),
        migrations.CreateModel(
            name='HistoricalBotListApi',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('method', models.IntegerField(blank=True, null=True)),
                ('feature', models.IntegerField(blank=True, null=True)),
                ('supported_fields', models.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(blank=True, db_column='url', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='NGBBAdmin.botlist')),
            ],
            options={
                'verbose_name': 'historical bot list api',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
