# Generated by Django 3.1.7 on 2021-03-16 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0002_auto_20210316_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbotlistapi',
            name='id',
        ),
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('b8192b55-0c71-4c12-8512-1ce104f4d8f6')),
        ),
    ]
