# Generated by Django 3.1.7 on 2021-03-16 12:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0002_historicalbotlist_historicalbotlistapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('e6770033-68f6-4bc5-90eb-76fb87a32494')),
        ),
    ]
