# Generated by Django 3.1.7 on 2021-03-16 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0003_auto_20210316_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('fa6ae5b5-532a-49b6-a8c1-4cfc4cfd792d')),
        ),
        migrations.AlterField(
            model_name='historicalbotlist',
            name='queue',
            field=models.BooleanField(default=False),
        ),
    ]
