# Generated by Django 3.1.7 on 2021-03-16 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0003_auto_20210316_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbotlistapi',
            name='api_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('82a03e1b-7bea-403a-8ade-4476a8bc4485')),
        ),
        migrations.AlterField(
            model_name='historicalbotlistapi',
            name='feature',
            field=models.IntegerField(blank=True, choices=[(1, 'Get Bot'), (2, 'Post Stats')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalbotlistapi',
            name='method',
            field=models.IntegerField(blank=True, choices=[(1, 'GET'), (2, 'POST'), (3, 'PATCH'), (4, 'PUT'), (5, 'DELETE')], null=True),
        ),
    ]
