# Generated by Django 3.1.7 on 2021-03-16 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0004_auto_20210316_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('3f38c7c5-59df-47bb-846a-cabfef4fc8cc')),
        ),
        migrations.AlterField(
            model_name='historicalbotlistapi',
            name='api_path',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='historicalbotlistapi',
            name='feature',
            field=models.IntegerField(choices=[(1, 'Get Bot'), (2, 'Post Stats')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalbotlistapi',
            name='method',
            field=models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PATCH'), (4, 'PUT'), (5, 'DELETE')], default=1),
        ),
    ]
