# Generated by Django 3.1.7 on 2021-03-16 12:26

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0006_auto_20210316_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('6850f3c0-2e38-4ac5-b705-59919c53866d')),
        ),
        migrations.AlterField(
            model_name='historicalbotlist',
            name='owners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
    ]
