# Generated by Django 3.1.7 on 2021-03-16 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0007_auto_20210316_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbotlist',
            name='id',
            field=models.IntegerField(blank=True, db_index=True, default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbotlistapi',
            name='id',
            field=models.IntegerField(blank=True, db_index=True, default=-10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('94736067-4c9e-4b93-a5c3-807a90ff39d7')),
        ),
    ]
