# Generated by Django 3.1.7 on 2021-03-16 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0008_auto_20210316_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('a01118a6-644f-46b4-a4dd-d86f91a437d8')),
        ),
        migrations.AlterField(
            model_name='historicalbotlistapi',
            name='url',
            field=models.TextField(default=1000),
            preserve_default=False,
        ),
    ]
