# Generated by Django 3.1.7 on 2021-03-16 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGBBAdmin', '0009_auto_20210316_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbotlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('9c776dcf-2393-4ac9-bcc5-cad68c16ddf5')),
        ),
        migrations.AlterField(
            model_name='historicalbotlistapi',
            name='url',
            field=models.ForeignKey(blank=True, db_column='url', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='NGBBAdmin.botlist'),
        ),
        migrations.CreateModel(
            name='HistoricalBotListFeature',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('iname', models.TextField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('positive', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bot list feature',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
