# Generated by Django 3.1.7 on 2021-03-16 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0011_auto_20210316_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('a8c6e2f0-8eb8-47ec-8b4e-dd5c73282b8e')),
        ),
        migrations.AlterField(
            model_name='historicalbotlistfeature',
            name='iname',
            field=models.TextField(db_index=True, verbose_name='Internal Name'),
        ),
        migrations.AlterField(
            model_name='historicalbotlistfeature',
            name='positive',
            field=models.IntegerField(choices=[(0, 'Negative'), (1, 'Positive'), (2, 'Neutral')], default=2),
            preserve_default=False,
        ),
    ]
