# Generated by Django 3.1.7 on 2021-03-16 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0012_auto_20210316_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbotlistfeature',
            name='feature_id',
            field=models.IntegerField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('0c616d47-5815-44bb-bb2f-4c38623acfce')),
        ),
    ]
