# Generated by Django 3.1.7 on 2021-03-16 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGBBAdmin', '0013_auto_20210316_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbotlist',
            name='api_token',
            field=models.TextField(default=uuid.UUID('9eabd040-3287-4bb2-8b3e-2ba42eb74402')),
        ),
        migrations.AlterField(
            model_name='historicalbotlistapi',
            name='supported_fields',
            field=models.JSONField(blank=True, help_text='Format of each key, valae is NGBB_KEY: LIST_KEY where NGBB_KEY is the key used by NGBB and LIST_KEY is the key used by the list', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbotlistfeature',
            name='feature_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
